import { useEffect, useRef, type ClipboardEvent } from 'react';
import ReactMarkdown from 'react-markdown';

export type ChatMessage = {
    content: string;
    role: 'user' | 'bot';
};

type Props = {
    messages: ChatMessage[];
};

const Conversation = ({ messages }: Props) => {
    const lastMessageRef = useRef<HTMLDivElement | null>(null);

    useEffect(() => {
        lastMessageRef.current?.scrollIntoView({ behavior: 'smooth' });
    }, [messages]);

    // Filter whitespace (generated by HTML document) when user tries to copy a message:
    const onCopyMessage = (e: ClipboardEvent) => {
        const text = window.getSelection()?.toString().trim();
        if (text) {
            e.preventDefault();
            e.clipboardData.setData('text/plain', text);
        }
    };

    return (
        <>
            {messages.map((message, index) => (
                <div
                    key={index}
                    onCopy={onCopyMessage}
                    ref={index === messages.length - 1 ? lastMessageRef : null}
                    className={`px-3 py-1 rounded-xl ${message.role === 'user' ? 'bg-blue-100 self-end' : 'bg-gray-100 self-start'}`}
                >
                    <ReactMarkdown>{message.content}</ReactMarkdown>
                </div>
            ))}
        </>
    );
};

export default Conversation;
