import axios from 'axios';
import {
    useEffect,
    useRef,
    useState,
    type ClipboardEvent,
    type KeyboardEvent,
} from 'react';
import ReactMarkdown from 'react-markdown';
import { FaArrowRightLong } from 'react-icons/fa6';
import { useForm } from 'react-hook-form';
import { Button } from './ui/button.tsx';
import Separator from './Separator.tsx';
import LoadingAnimation from './LoadingAnimation.tsx';

type FormData = {
    prompt: string;
};

type ChatResponse = {
    message: string;
};

type ChatMessage = {
    content: string;
    role: 'user' | 'bot';
};

const ChatBot = () => {
    const [messages, setMessages] = useState<ChatMessage[]>([]);
    const [isLoading, setIsLoading] = useState(false);
    const formRef = useRef<HTMLFormElement | null>(null);
    const clientId = useRef(crypto.randomUUID());
    const { register, handleSubmit, reset, formState } = useForm<FormData>();

    useEffect(() => {
        formRef.current?.scrollIntoView({ behavior: 'smooth' });
    }, [messages]);

    const onSubmit = async ({ prompt }: FormData) => {
        setMessages((prev) => [...prev, { content: prompt, role: 'user' }]);

        reset();

        setIsLoading(true);
        const { data } = await axios.post<ChatResponse>('/api/chat', {
            prompt,
            clientId: clientId.current,
        });

        setMessages((prev) => [
            ...prev,
            { content: data.message, role: 'bot' },
        ]);
        setIsLoading(false);
    };

    const onKeyDown = (e: KeyboardEvent<HTMLFormElement>) => {
        if (e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault();
            handleSubmit(onSubmit)();
        }
    };

    // Filter whitespace (generated by HTML document) when user tries to copy a message:
    const onCopyMessage = (e: ClipboardEvent) => {
        const text = window.getSelection()?.toString().trim();
        if (text) {
            e.preventDefault();
            e.clipboardData.setData('text/plain', text);
        }
    };

    return (
        <div>
            <div className="flex flex-col gap-1">
                {messages.map((message, index) => (
                    <p
                        key={index}
                        onCopy={onCopyMessage}
                        className={`px-3 py-1 rounded-xl ${message.role === 'user' ? 'bg-blue-100 self-end' : 'bg-gray-100 self-start'}`}
                    >
                        <ReactMarkdown>{message.content}</ReactMarkdown>
                    </p>
                ))}
                {isLoading ? <LoadingAnimation /> : null}
            </div>
            <Separator />
            <form
                onSubmit={handleSubmit(onSubmit)}
                onKeyDown={onKeyDown}
                ref={formRef}
                className="flex flex-col gap-2 items-end border-2 p-4 rounded-xl"
            >
                <textarea
                    {...register('prompt', {
                        required: true,
                        validate: (data) => data.trim().length > 0,
                    })}
                    className="w-full focus:outline-0 resize-none"
                    placeholder="Ask anything!"
                    maxLength={1000}
                />
                <Button
                    disabled={!formState.isValid}
                    className="rounded-full w-10 h-10"
                >
                    <FaArrowRightLong />
                </Button>
            </form>
        </div>
    );
};

export default ChatBot;
